# Generated by Django 5.2.8 on 2025-12-06 14:00

import django.db.models.deletion
import ttmm_26.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('day', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2')])),
                ('image', models.FileField(blank=True, upload_to=ttmm_26.models.upload_image)),
                ('ppt', models.FileField(blank=True, upload_to=ttmm_26.models.upload_ppt)),
                ('bid_overview', models.TextField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.FileField(blank=True, null=True, upload_to=ttmm_26.models.upload_image)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ttmm_investor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_name', models.CharField(blank=True, max_length=30, null=True)),
                ('day', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2')])),
                ('current_scene', models.IntegerField(choices=[(0, 'none'), (1, 'bidding'), (2, 'after_bidding')])),
                ('allow_bids', models.BooleanField(default=False)),
                ('force_reload', models.BooleanField(default=False)),
                ('current_startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ttmm_26.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding', models.IntegerField(blank=True, default=0)),
                ('final_submit', models.BooleanField(blank=True, default=False)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttmm_26.investor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttmm_26.startup')),
            ],
        ),
    ]
