# Generated by Django 5.2.8 on 2025-12-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmm_26', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='allow_bids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='status',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'bidding'), (2, 'after_bidding')], default=0),
        ),
        migrations.AlterField(
            model_name='portalcontrol',
            name='current_scene',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'bidding'), (2, 'after_bidding')], default=0),
        ),
    ]
