# Generated by Django 5.2.8 on 2025-12-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmm_26', '0002_startup_allow_bids_startup_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='allow_bids',
        ),
        migrations.AlterField(
            model_name='portalcontrol',
            name='current_scene',
            field=models.IntegerField(choices=[(0, 'Closed (None)'), (1, 'Bidding (Active)'), (2, 'Bidding Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.IntegerField(choices=[(0, 'Closed (None)'), (1, 'Bidding (Active)'), (2, 'Bidding Completed')], default=0),
        ),
    ]
