# Generated by Django 5.2.8 on 2025-12-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttmm_26', '0003_remove_startup_allow_bids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='status',
        ),
        migrations.AlterField(
            model_name='portalcontrol',
            name='current_scene',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'bidding'), (2, 'after_bidding')]),
        ),
    ]
